# Generated by Django 6.0.4 on 2026-09-02 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('price', models.IntegerField(help_text='Base price in Naira (excluding N100 fee)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DAILY_FREE', 'Daily Free Allocation'), ('DAILY_PRO', 'Daily Pro Allocation'), ('PURCHASE', 'Purchased Credits'), ('ADMIN', 'Admin Adjustment'), ('PROMOTIONAL', 'Promotional'), ('REFUND', 'Refund')], max_length=20)),
                ('original_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null for non-expiring credits (e.g. purchases)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'remaining_amount', 'expires_at'], name='credits_cre_user_id_face1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AI_USAGE', 'AI Usage'), ('DAILY_ALLOCATION', 'Daily Allocation'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('EXPIRATION', 'Expiration'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('action', models.CharField(blank=True, help_text='e.g. CHAT, GENERATE_MCQ', max_length=100)),
                ('reference_id', models.CharField(blank=True, help_text='Used for idempotency, e.g. request ID or payment ref', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='credits_cre_user_id_8fd4cc_idx'), models.Index(fields=['user', 'reference_id'], name='credits_cre_user_id_fecfea_idx')],
            },
        ),
    ]
