# Generated by Django 6.0.4 on 2026-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlot',
            name='source',
            field=models.CharField(choices=[('DAILY_FREE', 'Daily Free Allocation'), ('DAILY_PRO', 'Daily Pro Allocation'), ('DAILY_CLASS_HEAD', 'Daily Class Head Allocation'), ('DAILY_MATERIAL_UPLOADER', 'Daily Material Uploader Allocation'), ('PURCHASE', 'Purchased Credits'), ('ADMIN', 'Admin Adjustment'), ('PROMOTIONAL', 'Promotional'), ('REFUND', 'Refund')], max_length=50),
        ),
    ]
