import os
def w(path, c):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    open(path,'w',encoding='utf-8').write(c)
    print(f'Created {path}')
Q=chr(34)
e=[]
e.append(Q+'use client'+Q+';')
e.append('')
e.append('import { useEffect, useCallback } from '+Q+'react'+Q+';')
e.append('import { useRouter } from '+Q+'next/navigation'+Q+';')
e.append('import { motion, AnimatePresence } from '+Q+'framer-motion'+Q+';')
e.append('import { ChevronLeft, ChevronRight, Send, Menu, X, AlertTriangle } from '+Q+'lucide-react'+Q+';')
e.append('import { Button } from '+Q+'@/components/ui/button'+Q+';')
e.append('import { Card, CardContent, CardHeader, CardTitle } from '+Q+'@/components/ui/card'+Q+';')
e.append('import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '+Q+'@/components/ui/sheet'+Q+';')
e.append('import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '+Q+'@/components/ui/alert-dialog'+Q+';')
e.append('import { Separator } from '+Q+'@/components/ui/separator'+Q+';')
e.append('import { useToast } from '+Q+'@/components/ui/use-toast'+Q+';')
e.append('import { useAppDispatch, useAppSelector } from '+Q+'@/store/hooks'+Q+';')
e.append('import {')
e.append('  loadAttempt, saveAnswer, flagQuestion, submitAttempt, autoSubmitAttempt,')
e.append('  navigateToQuestion, nextQuestion, prevQuestion,')
e.append('  setMCQAnswer, setTheoryAnswer, toggleFlag, tickTimer, startTimer, resetAttempt')
e.append('} from '+Q+'@/store/quiz-attempt-slice'+Q+';')
e.append('import { ExamTimer } from '+Q+'@/components/quiz/exam-timer'+Q+';')
e.append('import { MCQQuestionCard } from '+Q+'@/components/quiz/mcq-question-card'+Q+';')
e.append('import { TheoryQuestionCard } from '+Q+'@/components/quiz/theory-question-card'+Q+';')
e.append('import { QuestionNavigator } from '+Q+'@/components/quiz/question-navigator'+Q+';')
e.append('')
e.append('interface ExamInterfacePageProps {')
e.append('  params: { id: string };')
e.append('}')
e.append('')
e.append('export default function ExamInterfacePage({ params }: ExamInterfacePageProps) {')
e.append('  const router = useRouter();')
e.append('  const { toast } = useToast();')
e.append('  const dispatch = useAppDispatch();')
e.append('  const { currentAttempt, currentQuestionIndex, answers, questionStatuses, timeRemainingSeconds, timerActive, loading, submitting, isSubmitted } = useAppSelector((s) => s.quizAttempt);')
e.append('')
e.append('  useEffect(() => {')
e.append('    dispatch(loadAttempt(params.id)).then(() => { dispatch(startTimer()); });')
e.append('    return () => { dispatch(resetAttempt()); };')
e.append('  }, [params.id, dispatch]);')
e.append('')
e.append('  useEffect(() => {')
e.append('    if (isSubmitted) { router.push(`/quiz/attempt/${params.id}/results`); }')
e.append('  }, [isSubmitted, params.id, router]);')
e.append('')
e.append('  const handleTick = useCallback(() => { dispatch(tickTimer()); }, [dispatch]);')
e.append('')
e.append('  const handleTimerExpire = useCallback(() => {')
e.append('    toast({ title: '+Q+'Time is up!'+Q+', description: '+Q+'Your exam has been automatically submitted.'+Q+' });')
e.append('    dispatch(autoSubmitAttempt(params.id));')
e.append('  }, [dispatch, params.id, toast]);')
e.append('')
e.append('  const handleMCQSelect = (questionId: string, option: string) => {')
e.append('    dispatch(setMCQAnswer({ questionId, option }));')
e.append('    dispatch(saveAnswer({ attemptId: params.id, answer: { question_id: questionId, selected_option: option, time_taken_seconds: 30 } }));')
e.append('  };')
e.append('')
e.append('  const handleTheoryChange = (questionId: string, text: string) => {')
e.append('    dispatch(setTheoryAnswer({ questionId, text }));')
e.append('  };')
e.append('')
e.append('  const handleTheoryBlur = (questionId: string) => {')
e.append('    const answer = answers[questionId];')
e.append('    if (answer?.text_answer) {')
e.append('      dispatch(saveAnswer({ attemptId: params.id, answer: { question_id: questionId, text_answer: answer.text_answer, time_taken_seconds: 60 } }));')
e.append('    }')
e.append('  };')
e.append('')
e.append('  const handleFlag = (questionId: string) => {')
e.append('    dispatch(toggleFlag(questionId));')
e.append('    dispatch(flagQuestion({ attemptId: params.id, questionId }));')
e.append('  };')
e.append('')
e.append('  const handleSubmit = async () => {')
e.append('    await dispatch(submitAttempt(params.id));')
e.append('  };')
e.append('')
e.append('  if (loading || !currentAttempt) {')
e.append('    return (')
e.append('      <div className='+Q+'min-h-screen flex items-center justify-center bg-background'+Q+'>')
e.append('        <div className='+Q+'text-center space-y-4'+Q+'>')
e.append('          <div className='+Q+'w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto'+Q+'></div>')
e.append('          <p className='+Q+'text-muted-foreground'+Q+'>Loading your exam...</p>')
e.append('        </div>')
e.append('      </div>')
e.append('    );')
e.append('  }')
e.append('')
e.append('  const questions = currentAttempt.questions;')
e.append('  const currentQuestion = questions[currentQuestionIndex];')
e.append('  const questionIds = questions.map((q) => q.id);')
e.append('  const answeredCount = Object.values(questionStatuses).filter((s) => s === '+Q+'answered'+Q+').length;')
e.append('  const totalSeconds = currentAttempt.duration_minutes ? currentAttempt.duration_minutes * 60 : 0;')
e.append('')
e.append('  return (')
e.append('    <div className='+Q+'min-h-screen bg-background flex flex-col'+Q+'>')
e.append('      {/* Top Nav */}')
e.append('      <header className='+Q+'sticky top-0 z-50 bg-card/95 backdrop-blur border-b px-4 py-3'+Q+'>')
e.append('        <div className='+Q+'max-w-6xl mx-auto flex items-center justify-between gap-4'+Q+'>')
e.append('          <div className='+Q+'flex items-center gap-3'+Q+'>')
e.append('            <Sheet>')
e.append('              <SheetTrigger asChild>')
e.append('                <Button variant='+Q+'outline'+Q+' size='+Q+'icon'+Q+' className='+Q+'md:hidden'+Q+'><Menu className='+Q+'w-4 h-4'+Q+' /></Button>')
e.append('              </SheetTrigger>')
e.append('              <SheetContent side='+Q+'left'+Q+' className='+Q+'w-80'+Q+'>')
e.append('                <SheetHeader><SheetTitle>Question Navigator</SheetTitle></SheetHeader>')
e.append('                <div className='+Q+'mt-4'+Q+'>')
e.append('                  <QuestionNavigator totalQuestions={questions.length} currentIndex={currentQuestionIndex} statuses={questionStatuses} questionIds={questionIds} onNavigate={(i) => dispatch(navigateToQuestion(i))} />')
e.append('                </div>')
e.append('              </SheetContent>')
e.append('            </Sheet>')
e.append('            <div>')
e.append('              <h1 className='+Q+'font-semibold text-sm'+Q+'>{currentAttempt.subject_name || '+Q+'Quiz'+Q+'}</h1>')
e.append('              <p className='+Q+'text-xs text-muted-foreground capitalize'+Q+'>{currentAttempt.exam_type} exam</p>')
e.append('            </div>')
e.append('          </div>')
e.append('          <div className='+Q+'flex items-center gap-3'+Q+'>')
e.append('            {currentAttempt.is_timed && timeRemainingSeconds !== null && (')
e.append('              <ExamTimer totalSeconds={totalSeconds} remainingSeconds={timeRemainingSeconds} onTick={handleTick} onExpire={handleTimerExpire} active={timerActive} />')
e.append('            )}')
e.append('            <AlertDialog>')
e.append('              <AlertDialogTrigger asChild>')
e.append('                <Button size='+Q+'sm'+Q+' className='+Q+'gap-2'+Q+' disabled={submitting}>')
e.append('                  {submitting ? <><div className='+Q+'w-3 h-3 border-2 border-current border-t-transparent rounded-full animate-spin'+Q+'></div> Submitting...</> : <><Send className='+Q+'w-3.5 h-3.5'+Q+' />Submit</> }')
e.append('                </Button>')
e.append('              </AlertDialogTrigger>')
e.append('              <AlertDialogContent>')
e.append('                <AlertDialogHeader>')
e.append('                  <AlertDialogTitle>Submit your exam?</AlertDialogTitle>')
e.append('                  <AlertDialogDescription>You have answered {answeredCount} of {questions.length} questions. This action cannot be undone.</AlertDialogDescription>')
e.append('                </AlertDialogHeader>')
e.append('                <AlertDialogFooter>')
e.append('                  <AlertDialogCancel>Review First</AlertDialogCancel>')
e.append('                  <AlertDialogAction onClick={handleSubmit}>Submit Exam</AlertDialogAction>')
e.append('                </AlertDialogFooter>')
e.append('              </AlertDialogContent>')
e.append('            </AlertDialog>')
e.append('          </div>')
e.append('        </div>')
e.append('      </header>')
e.append('')
e.append('      {/* Main Content */}')
e.append('      <div className='+Q+'flex-1 max-w-6xl mx-auto w-full px-4 py-6 grid grid-cols-1 md:grid-cols-[1fr_280px] gap-6'+Q+'>')
e.append('        {/* Question Area */}')
e.append('        <Card className='+Q+'h-fit'+Q+'>')
e.append('          <CardContent className='+Q+'pt-6 pb-8 px-6'+Q+'>')
e.append('            <AnimatePresence mode='+Q+'wait'+Q+'>')
e.append('              {currentQuestion.question_type === '+Q+'mcq'+Q+' ? (')
e.append('                <MCQQuestionCard')
e.append('                  key={currentQuestion.id}')
e.append('                  question={currentQuestion}')
e.append('                  questionNumber={currentQuestionIndex + 1}')
e.append('                  totalQuestions={questions.length}')
e.append('                  selectedOption={answers[currentQuestion.id]?.selected_option}')
e.append('                  isFlagged={questionStatuses[currentQuestion.id] === '+Q+'flagged'+Q+'}')
e.append('                  onSelect={(opt) => handleMCQSelect(currentQuestion.id, opt)}')
e.append('                  onFlag={() => handleFlag(currentQuestion.id)}')
e.append('                />')
e.append('              ) : (')
e.append('                <TheoryQuestionCard')
e.append('                  key={currentQuestion.id}')
e.append('                  question={currentQuestion}')
e.append('                  questionNumber={currentQuestionIndex + 1}')
e.append('                  totalQuestions={questions.length}')
e.append('                  answer={answers[currentQuestion.id]?.text_answer || '+Q+Q+'}')
e.append('                  isFlagged={questionStatuses[currentQuestion.id] === '+Q+'flagged'+Q+'}')
e.append('                  onChange={(text) => handleTheoryChange(currentQuestion.id, text)}')
e.append('                  onFlag={() => handleFlag(currentQuestion.id)}')
e.append('                />')
e.append('              )}')
e.append('            </AnimatePresence>')
e.append('          </CardContent>')
e.append('')
e.append('          {/* Navigation footer */}')
e.append('          <div className='+Q+'border-t px-6 py-4 flex items-center justify-between'+Q+'>')
e.append('            <Button variant='+Q+'outline'+Q+' onClick={() => dispatch(prevQuestion())} disabled={currentQuestionIndex === 0} className='+Q+'gap-2'+Q+'>')
e.append('              <ChevronLeft className='+Q+'w-4 h-4'+Q+' />Previous')
e.append('            </Button>')
e.append('            <span className='+Q+'text-sm text-muted-foreground'+Q+'>')
e.append('              {currentQuestionIndex + 1} / {questions.length}')
e.append('            </span>')
e.append('            <Button onClick={() => dispatch(nextQuestion())} disabled={currentQuestionIndex === questions.length - 1} className='+Q+'gap-2'+Q+'>')
e.append('              Next<ChevronRight className='+Q+'w-4 h-4'+Q+' />')
e.append('            </Button>')
e.append('          </div>')
e.append('        </Card>')
e.append('')
e.append('        {/* Navigator Sidebar (desktop) */}')
e.append('        <div className='+Q+'hidden md:block space-y-4'+Q+'>')
e.append('          <Card>')
e.append('            <CardHeader className='+Q+'pb-3'+Q+'>')
e.append('              <CardTitle className='+Q+'text-sm'+Q+'>Questions</CardTitle>')
e.append('            </CardHeader>')
e.append('            <CardContent>')
e.append('              <QuestionNavigator totalQuestions={questions.length} currentIndex={currentQuestionIndex} statuses={questionStatuses} questionIds={questionIds} onNavigate={(i) => dispatch(navigateToQuestion(i))} />')
e.append('            </CardContent>')
e.append('          </Card>')
e.append('        </div>')
e.append('      </div>')
e.append('    </div>')
e.append('  );')
e.append('}')
w('app/(app)/quiz/attempt/[id]/page.tsx', chr(10).join(e))
