import os
def w(path, c):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    open(path,'w',encoding='utf-8').write(c)
    print(f'Created {path}')
Q=chr(34)
t=[]
t.append(Q+'use client'+Q+';')
t.append('import { motion } from '+Q+'framer-motion'+Q+';')
t.append('import { Flag, PenLine, AlignLeft } from '+Q+'lucide-react'+Q+';')
t.append('import { Badge } from '+Q+'@/components/ui/badge'+Q+';')
t.append('import { Button } from '+Q+'@/components/ui/button'+Q+';')
t.append('import { Textarea } from '+Q+'@/components/ui/textarea'+Q+';')
t.append('import { cn } from '+Q+'@/lib/utils'+Q+';')
t.append('import type { QuizQuestion } from '+Q+'@/store/quiz-attempt-slice'+Q+';')
t.append('')
t.append('interface TheoryQuestionCardProps {')
t.append('  question: QuizQuestion;')
t.append('  questionNumber: number;')
t.append('  totalQuestions: number;')
t.append('  answer: string;')
t.append('  isFlagged: boolean;')
t.append('  onChange: (text: string) => void;')
t.append('  onFlag: () => void;')
t.append('}')
t.append('')
t.append('export function TheoryQuestionCard({ question, questionNumber, totalQuestions, answer, isFlagged, onChange, onFlag }: TheoryQuestionCardProps) {')
t.append('  const wordCount = answer.trim().split(/\s+/).filter(Boolean).length;')
t.append('  const hasEnough = wordCount >= 30;')
t.append('  return (')
t.append('    <motion.div key={question.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className='+Q+'space-y-6'+Q+'>')
t.append('      <div className='+Q+'flex items-start justify-between gap-4'+Q+'>')
t.append('        <div className='+Q+'flex-1'+Q+'>')
t.append('          <div className='+Q+'flex flex-wrap items-center gap-2 mb-3'+Q+'>')
t.append('            <Badge variant='+Q+'outline'+Q+' className='+Q+'text-xs'+Q+'>Question {questionNumber} of {totalQuestions}</Badge>')
t.append('            <Badge className='+Q+'text-xs bg-emerald-100 text-emerald-700 border border-emerald-200'+Q+'><PenLine className='+Q+'w-3 h-3 mr-1'+Q+' />Theory</Badge>')
t.append('            <Badge variant='+Q+'secondary'+Q+' className='+Q+'text-xs capitalize'+Q+'>{question.difficulty}</Badge>')
t.append('          </div>')
t.append('          <p className='+Q+'text-lg font-medium leading-relaxed'+Q+'>{question.question_text}</p>')
t.append('        </div>')
t.append('        <Button variant='+Q+'ghost'+Q+' size='+Q+'icon'+Q+' onClick={onFlag} className={cn('+Q+'flex-shrink-0 rounded-full'+Q+', isFlagged ? '+Q+'text-amber-500 bg-amber-50'+Q+' : '+Q+'text-muted-foreground'+Q+')}><Flag className='+Q+'w-4 h-4'+Q+' /></Button>')
t.append('      </div>')
t.append('      <div className='+Q+'p-3 rounded-lg bg-emerald-50 border border-emerald-100 flex items-start gap-2'+Q+'>')
t.append('        <AlignLeft className='+Q+'w-4 h-4 text-emerald-600 mt-0.5 flex-shrink-0'+Q+' />')
t.append('        <p className='+Q+'text-sm text-emerald-700'+Q+'>Write a detailed answer. Aim for at least 30 words. AI will evaluate your response.</p>')
t.append('      </div>')
t.append('      <div className='+Q+'space-y-2'+Q+'>')
t.append('        <Textarea value={answer} onChange={(e) => onChange(e.target.value)} placeholder='+Q+'Start writing your answer here...'+Q+' className='+Q+'min-h-[220px] resize-y text-base leading-relaxed'+Q+' autoFocus />')
t.append('        <div className='+Q+'flex items-center justify-between px-1'+Q+'>')
t.append('          <span className={cn('+Q+'text-xs transition-colors'+Q+', hasEnough ? '+Q+'text-emerald-600'+Q+' : '+Q+'text-muted-foreground'+Q+')}>{wordCount} word{wordCount !== 1 ? '+Q+'s'+Q+' : '+Q+Q+'}{ !hasEnough ? '+Q+' (30+ recommended)'+Q+' : '+Q+' check'+Q+'}</span>')
t.append('          <span className='+Q+'text-xs text-muted-foreground'+Q+'>{answer.length} chars</span>')
t.append('        </div>')
t.append('      </div>')
t.append('    </motion.div>')
t.append('  );')
t.append('}')
w('components/quiz/theory-question-card.tsx', chr(10).join(t))
