import os, sys

def w(path, content):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(content)
    print(f'Created {path}')

Q = chr(34)

# Question Navigator
nav = []
nav.append(Q+'use client'+Q+';')
nav.append('')
nav.append('import { motion } from '+Q+'framer-motion'+Q+';')
nav.append('import { Flag, Check } from '+Q+'lucide-react'+Q+';')
nav.append('import { cn } from '+Q+'@/lib/utils'+Q+';')
nav.append('import type { QuestionStatus } from '+Q+'@/store/quiz-attempt-slice'+Q+';')
nav.append('')
nav.append('interface QuestionNavigatorProps {')
nav.append('  totalQuestions: number;')
nav.append('  currentIndex: number;')
nav.append('  statuses: Record<string, QuestionStatus>;')
nav.append('  questionIds: string[];')
nav.append('  onNavigate: (index: number) => void;')
nav.append('}')
nav.append('')
nav.append('export function QuestionNavigator({ totalQuestions, currentIndex, statuses, questionIds, onNavigate }: QuestionNavigatorProps) {')
nav.append('  const answered = questionIds.filter((id) => statuses[id] === '+Q+'answered'+Q+').length;')
nav.append('  const flagged = questionIds.filter((id) => statuses[id] === '+Q+'flagged'+Q+').length;')
nav.append('  return (')
nav.append('    <div className='+Q+'space-y-4'+Q+'>')
nav.append('      <div className='+Q+'grid grid-cols-3 gap-2 text-center'+Q+'>')
nav.append('        <div className='+Q+'p-2 rounded-lg bg-primary/10'+Q+'><div className='+Q+'text-xl font-bold text-primary'+Q+'>{answered}</div><div className='+Q+'text-xs text-muted-foreground'+Q+'>Answered</div></div>')
nav.append('        <div className='+Q+'p-2 rounded-lg bg-amber-50'+Q+'><div className='+Q+'text-xl font-bold text-amber-600'+Q+'>{flagged}</div><div className='+Q+'text-xs text-muted-foreground'+Q+'>Flagged</div></div>')
nav.append('        <div className='+Q+'p-2 rounded-lg bg-muted'+Q+'><div className='+Q+'text-xl font-bold text-muted-foreground'+Q+'>{totalQuestions - answered - flagged}</div><div className='+Q+'text-xs text-muted-foreground'+Q+'>Remaining</div></div>')
nav.append('      </div>')
nav.append('      <div className='+Q+'grid grid-cols-5 gap-1.5'+Q+'>')
nav.append('        {questionIds.map((id, i) => {')
nav.append('          const status = statuses[id] ?? '+Q+'unanswered'+Q+';')
nav.append('          return (')
nav.append('            <motion.button key={id} whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.95 }} onClick={() => onNavigate(i)}')
nav.append('              className={cn('+Q+'w-9 h-9 rounded-lg text-xs font-semibold flex items-center justify-center border transition-all'+Q+',')
nav.append('                i === currentIndex ? '+Q+'ring-2 ring-primary ring-offset-1'+Q+' : '+Q+Q+',')
nav.append('                status === '+Q+'answered'+Q+' ? '+Q+'bg-primary text-primary-foreground border-primary'+Q)
nav.append('                  : status === '+Q+'flagged'+Q+' ? '+Q+'bg-amber-100 text-amber-700 border-amber-300'+Q)
nav.append('                  : '+Q+'bg-muted text-muted-foreground hover:bg-accent border-border'+Q+')}>')
nav.append('              {status === '+Q+'answered'+Q+' ? <Check className='+Q+'w-3.5 h-3.5'+Q+' /> : status === '+Q+'flagged'+Q+' ? <Flag className='+Q+'w-3.5 h-3.5'+Q+' /> : i + 1}')
nav.append('            </motion.button>')
nav.append('          );')
nav.append('        })}')
nav.append('      </div>')
nav.append('    </div>')
nav.append('  );')
nav.append('}')
w('components/quiz/question-navigator.tsx', chr(10).join(nav))
