# Generated by Django 6.0.6 on 2026-08-28 02:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated', models.IntegerField(default=60)),
                ('used', models.IntegerField(default=0)),
                ('period_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('tier_at_grant', models.CharField(default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI credit account',
            },
        ),
        migrations.CreateModel(
            name='DashboardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('RESOURCE_STUDIED', 'Resource studied'), ('STUDY_SESSION_COMPLETED', 'Study session completed'), ('QUIZ_COMPLETED', 'Quiz completed'), ('QUESTION_ANSWERED', 'Question answered'), ('FLASHCARD_REVIEWED', 'Flashcard reviewed'), ('STEEPLECHASE_COMPLETED', 'Steeplechase completed'), ('HISTOLOGY_COMPLETED', 'Histology completed'), ('BRAIN_BATTLE_COMPLETED', 'Brain battle completed'), ('PLANNER_TASK_COMPLETED', 'Planner task completed')], max_length=40)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('resource_type', models.CharField(blank=True, max_length=40)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.block')),
                ('sub_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.subblock')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FLASHCARDS_DUE', 'Flashcards due'), ('FLASHCARDS_MISSED', 'Missed flashcards'), ('PLANNER_UPCOMING', 'Planned session starting'), ('PLANNER_MISSED', 'Planned session missed'), ('STUDY_GOAL', 'Daily study goal'), ('STREAK_AT_RISK', 'Streak at risk'), ('WEAK_AREA', 'Weak area needs revision'), ('QUESTIONS_READY', 'Generated questions ready'), ('BATTLE_INVITE', 'Brain battle invitation')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashcards_enabled', models.BooleanField(default=True)),
                ('planner_enabled', models.BooleanField(default=True)),
                ('study_goal_enabled', models.BooleanField(default=True)),
                ('streak_enabled', models.BooleanField(default=True)),
                ('weak_area_enabled', models.BooleanField(default=True)),
                ('browser_push_enabled', models.BooleanField(default=False)),
                ('push_subscription', models.JSONField(blank=True, default=dict)),
                ('quiet_hours_start', models.IntegerField(default=22)),
                ('quiet_hours_end', models.IntegerField(default=7)),
                ('max_per_day', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeRoundUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('STEEPLECHASE', 'Steeplechase'), ('HISTOLOGY', 'Histology')], max_length=20)),
                ('period', models.CharField(max_length=7)),
                ('rounds_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('STEEPLECHASE', 'Steeplechase'), ('HISTOLOGY', 'Histology')], max_length=20)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('station_ids', models.JSONField(default=list)),
                ('seconds_per_station', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('total_stations', models.IntegerField(default=0)),
                ('main_correct', models.IntegerField(default=0)),
                ('supporting_correct', models.IntegerField(default=0)),
                ('true_false_correct', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('timed_out_count', models.IntegerField(default=0)),
                ('section_breakdown', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('main_answer', models.TextField(blank=True)),
                ('main_correct', models.BooleanField(blank=True, null=True)),
                ('supporting_choice', models.IntegerField(blank=True, null=True)),
                ('supporting_correct', models.BooleanField(blank=True, null=True)),
                ('true_false_answer', models.BooleanField(blank=True, null=True)),
                ('true_false_correct', models.BooleanField(blank=True, null=True)),
                ('seconds_taken', models.IntegerField(default=0)),
                ('timed_out', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='curriculum.spotstation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.practicesession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.IntegerField(default=0)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_correct_at', models.DateTimeField(blank=True, null=True)),
                ('last_incorrect_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='curriculum.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exposure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SUBJECT', 'Subject'), ('BLOCK', 'Block'), ('SUB_BLOCK', 'Sub-block'), ('TOPIC', 'Topic')], max_length=12)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('attempted', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('mastery', models.FloatField(default=0.0)),
                ('priority', models.FloatField(db_index=True, default=0.0)),
                ('last_practised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curriculum.block')),
                ('sub_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curriculum.subblock')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curriculum.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curriculum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='XPAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('RESOURCE_STUDIED', 'Resource studied'), ('STUDY_SESSION_COMPLETED', 'Study session completed'), ('QUIZ_COMPLETED', 'Quiz completed'), ('QUESTION_ANSWERED', 'Question answered'), ('FLASHCARD_REVIEWED', 'Flashcard reviewed'), ('STEEPLECHASE_COMPLETED', 'Steeplechase completed'), ('HISTOLOGY_COMPLETED', 'Histology completed'), ('BRAIN_BATTLE_COMPLETED', 'Brain battle completed'), ('PLANNER_TASK_COMPLETED', 'Planner task completed')], max_length=40)),
                ('amount', models.IntegerField()),
                ('base_amount', models.IntegerField(default=0)),
                ('multiplier', models.FloatField(default=1.0)),
                ('capped', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('awarded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_awards', to='learning.learningevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CHAT', 'Tutor chat message'), ('EXPLAIN', 'Explain selection'), ('GENERATE_MCQ', 'Generate MCQs'), ('GENERATE_THEORY', 'Generate theory questions'), ('GENERATE_FLASHCARDS', 'Generate flashcards'), ('GRADE_THEORY', 'Grade a theory answer'), ('RESOURCES', 'Suggest resources'), ('STUDY_PLAN', 'Build a study plan'), ('DASHBOARD_MESSAGE', 'Dashboard message'), ('BATTLE_QUESTIONS', 'Brain battle questions')], max_length=32)),
                ('credits', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CHARGED', 'Charged'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='RESERVED', max_length=12)),
                ('resource_type', models.CharField(blank=True, max_length=40)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='learning_ai_user_id_cae35a_idx'), models.Index(fields=['user', 'action'], name='learning_ai_user_id_25cd09_idx'), models.Index(fields=['status'], name='learning_ai_status_c4fe5c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='unique_ai_usage_idempotency_key')],
            },
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', '-occurred_at'], name='learning_le_user_id_d9ecec_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'activity', '-occurred_at'], name='learning_le_user_id_e9ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'subject'], name='learning_le_user_id_d460ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-scheduled_for'], name='learning_no_user_id_f81247_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='learning_no_status_59fd7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='unique_notification_dedupe_key'),
        ),
        migrations.AlterUniqueTogether(
            name='practiceroundusage',
            unique_together={('user', 'mode', 'period')},
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'mode', '-started_at'], name='learning_pr_user_id_5e0b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'status'], name='learning_pr_user_id_6205f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practiceattempt',
            unique_together={('session', 'station')},
        ),
        migrations.AddIndex(
            model_name='questionexposure',
            index=models.Index(fields=['user', 'last_seen_at'], name='learning_qu_user_id_9cf9db_idx'),
        ),
        migrations.AddIndex(
            model_name='questionexposure',
            index=models.Index(fields=['user', 'times_seen'], name='learning_qu_user_id_f01a46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionexposure',
            unique_together={('user', 'question')},
        ),
        migrations.AddIndex(
            model_name='weakarea',
            index=models.Index(fields=['user', '-priority'], name='learning_we_user_id_35a35a_idx'),
        ),
        migrations.AddIndex(
            model_name='weakarea',
            index=models.Index(fields=['user', 'scope'], name='learning_we_user_id_4d3779_idx'),
        ),
        migrations.AddConstraint(
            model_name='weakarea',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'subject', 'block', 'sub_block', 'topic'), name='unique_weak_area_node_per_user'),
        ),
        migrations.AddIndex(
            model_name='xpaward',
            index=models.Index(fields=['user', '-awarded_at'], name='learning_xp_user_id_fa786a_idx'),
        ),
        migrations.AddIndex(
            model_name='xpaward',
            index=models.Index(fields=['user', 'reason', '-awarded_at'], name='learning_xp_user_id_213d5c_idx'),
        ),
    ]
