# Generated by Django 6.0.6 on 2026-08-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partially generated'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('mcq_target', models.IntegerField(default=50)),
                ('theory_target', models.IntegerField(default=10)),
                ('mcq_generated', models.IntegerField(default=0)),
                ('theory_generated', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_job', to='curriculum.slide')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='learning_qu_status_f428dd_idx')],
            },
        ),
    ]
