# Generated by Django 6.0.4 on 2026-09-02 02:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_questiongenerationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('price_naira', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_naira'],
            },
        ),
        migrations.AlterModelOptions(
            name='aicreditaccount',
            options={'verbose_name': 'AI credit account (deprecated)'},
        ),
        migrations.CreateModel(
            name='CreditLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DAILY_FREE', 'Daily free allocation'), ('DAILY_PRO', 'Daily Pro allocation'), ('PURCHASE', 'Purchased credits'), ('ADMIN', 'Admin grant'), ('PROMOTIONAL', 'Promotional grant'), ('REFUND', 'Refund')], max_length=20)),
                ('original_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('purchase_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit lot',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DAILY_ALLOCATION', 'Daily allocation'), ('AI_USAGE', 'AI usage'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('EXPIRATION', 'Expiration')], max_length=24)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('lot_breakdown', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='learning.creditlot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditlot',
            index=models.Index(fields=['user', 'expires_at'], name='learning_cr_user_id_25ea89_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlot',
            index=models.Index(fields=['user', 'source'], name='learning_cr_user_id_e6f2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditlot',
            index=models.Index(fields=['user', 'allocation_date'], name='learning_cr_user_id_c6d5a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditlot',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation_date__isnull', False)), fields=('user', 'source', 'allocation_date'), name='unique_daily_lot_per_user_source_date'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='learning_cr_user_id_26c5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', 'type'], name='learning_cr_user_id_2b74b7_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['type', '-created_at'], name='learning_cr_type_0464d7_idx'),
        ),
    ]
