# Generated by Django 6.0.4 on 2026-09-02 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_migrate_old_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='creditlot',
            name='learning_cr_user_id_25ea89_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditlot',
            name='learning_cr_user_id_e6f2d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditlot',
            name='learning_cr_user_id_c6d5a8_idx',
        ),
        migrations.RemoveConstraint(
            model_name='creditlot',
            name='unique_daily_lot_per_user_source_date',
        ),
        migrations.DeleteModel(
            name='CreditPackage',
        ),
        migrations.RemoveIndex(
            model_name='credittransaction',
            name='learning_cr_user_id_26c5f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='credittransaction',
            name='learning_cr_user_id_2b74b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='credittransaction',
            name='learning_cr_type_0464d7_idx',
        ),
        migrations.AlterModelOptions(
            name='aicreditaccount',
            options={'verbose_name': 'AI credit account'},
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='academic_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='community_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='system_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FLASHCARDS_DUE', 'Flashcards due'), ('FLASHCARDS_MISSED', 'Missed flashcards'), ('PLANNER_UPCOMING', 'Planned session starting'), ('PLANNER_MISSED', 'Planned session missed'), ('STUDY_GOAL', 'Daily study goal'), ('STREAK_AT_RISK', 'Streak at risk'), ('WEAK_AREA', 'Weak area needs revision'), ('QUESTIONS_READY', 'Generated questions ready'), ('BATTLE_INVITE', 'Brain battle invitation'), ('NEW_QUIZ', 'New Quiz Available'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('QUIZ_RESULT', 'Quiz Result Available'), ('NEW_PAST_Q', 'New Past Question'), ('NEW_FLASH_SET', 'New Flashcard Set'), ('GOAL_COMPLETED', 'Study Goal Completed'), ('NEW_SLIDES', 'New Slides Uploaded'), ('SLIDE_UPDATED', 'Slide Updated'), ('NEW_MATERIAL', 'New Class Material'), ('CLASS_ANNOUNCEMENT', 'Class Announcement'), ('HEAD_ANNOUNCEMENT', 'Class Head Announcement'), ('NEW_COMMENT', 'New Comment'), ('COMMENT_REPLY', 'Comment Reply'), ('POST_LIKED', 'Post Liked'), ('POST_COMMENTED', 'Post Commented'), ('MENTIONED', 'Mentioned'), ('NEW_FOLLOWER', 'New Follower'), ('ACCOUNT_SECURITY', 'Account Security'), ('WELCOME', 'Welcome'), ('SYSTEM_MSG', 'System Announcement'), ('MAINTENANCE', 'Maintenance'), ('FEATURE_UPDATE', 'Feature Update'), ('LEADERBOARD_CHANGE', 'Leaderboard Changed'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('BADGE_EARNED', 'Badge Earned'), ('STREAK_MILESTONE', 'Streak Milestone'), ('COMPETITION_START', 'Competition Started'), ('COMPETITION_END', 'Competition Ending')], max_length=32),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='reference_lot',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('user', 'endpoint')},
        ),
        migrations.DeleteModel(
            name='CreditLot',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
    ]
