/**
 * Emby brand asset registry.
 *
 * Every 3D icon and every mascot pose is declared here once, so components reference a
 * name (`"steeplechase"`, `"thinking"`) rather than a file path. That keeps asset paths
 * out of JSX, makes renames a one-line change, and lets TypeScript reject a pose or icon
 * that does not exist.
 *
 * Assets are generated by scripts/gen_brand.py and sized by scripts/optimize_brand.py.
 * The `.webp` files are what ship; the 1024px PNGs stay in the repo as the source.
 */

const ICON_BASE = "/brand/icons";
const MASCOT_BASE = "/brand/mascot";

/** 3D feature icons. Use these instead of emoji anywhere a concept needs a symbol. */
export const ICONS = {
  dashboard: "dashboard",
  read: "read",
  quiz: "quiz",
  flashcards: "flashcards",
  steeplechase: "steeplechase",
  histology: "histology",
  battle: "battle",
  analytics: "analytics",
  planner: "planner",
  premium: "premium",
  streak: "streak",
  xp: "xp",
  credits: "credits",
  notification: "notification",
  upload: "upload",
  community: "community",
  brain: "brain",
  target: "target",
  resource: "resource",
  profile: "profile",
} as const;

export type IconName = keyof typeof ICONS;

export function iconSrc(name: IconName, retina = false): string {
  return `${ICON_BASE}/${ICONS[name]}${retina ? "@2x" : ""}.webp`;
}

/**
 * Axo, the Emby mascot — an axolotl doctor.
 *
 * Poses are named for the *moment* they belong to rather than the drawing, so call sites
 * read as intent: `<Axo pose="thinking" />` while something loads, `<Axo pose="oops" />`
 * on an error. Keeping that mapping here means the art can change without touching UI.
 */
export const MASCOT_POSES = {
  hero: "axo-hero",
  thinking: "axo-thinking",
  celebrate: "axo-celebrate",
  sleeping: "axo-sleeping",
  teaching: "axo-teaching",
  magnifier: "axo-magnifier",
  microscope: "axo-microscope",
  clipboard: "axo-clipboard",
  oops: "axo-oops",
  trophy: "axo-trophy",
  books: "axo-books",
  flashcards: "axo-flashcards",
  rocket: "axo-rocket",
  peek: "axo-peek",
  timer: "axo-timer",
  heart: "axo-heart",
  empty: "axo-empty",
} as const;

export type AxoPose = keyof typeof MASCOT_POSES;

export function mascotSrc(pose: AxoPose, retina = false): string {
  return `${MASCOT_BASE}/${MASCOT_POSES[pose]}${retina ? "@2x" : ""}.webp`;
}

export const LOGO_MARK = "/brand/logo-mark.webp";

/**
 * Which pose fits which part of the app.
 *
 * Used by loading and empty states so the mascot reacts in a way that matches what the
 * student is doing, instead of showing the same picture everywhere.
 */
export const POSE_FOR_CONTEXT: Record<string, AxoPose> = {
  dashboard: "hero",
  read: "books",
  quiz: "clipboard",
  flashcards: "flashcards",
  steeplechase: "magnifier",
  histology: "microscope",
  battle: "trophy",
  analytics: "teaching",
  planner: "clipboard",
  premium: "rocket",
  community: "heart",
  profile: "hero",
};

/** Short, human lines Axo says while the app is busy. Rotated so it never nags. */
export const LOADING_LINES: readonly string[] = [
  "Thinking this through…",
  "Reading the slide…",
  "Checking the anatomy…",
  "Lining up your questions…",
  "Just a moment…",
  "Consulting my notes…",
];

export function loadingLine(seed = 0): string {
  return LOADING_LINES[Math.abs(seed) % LOADING_LINES.length];
}
