# Generated by Django 6.0.6, then hand-edited to make the unique `code` column safe to
# apply to a database that already contains battles.
#
# Adding `code` as unique in one step gives every existing row the same empty string and
# the constraint fails immediately. The column is therefore added without the constraint,
# backfilled with real codes, and only then made unique.

import django.db.models.deletion
from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    """Give every existing battle a unique join code."""
    import random
    import string

    BrainBattle = apps.get_model("curriculum", "BrainBattle")

    # The historical model has no methods, so the generator is repeated here rather than
    # imported — migrations must not depend on current model code.
    alphabet = "".join(
        c for c in string.ascii_uppercase + string.digits if c not in "O0I1LS5B8"
    )
    used = set(
        BrainBattle.objects.exclude(code="").values_list("code", flat=True)
    )

    for battle in BrainBattle.objects.filter(code="").iterator():
        while True:
            code = "".join(random.choices(alphabet, k=6))
            if code not in used:
                used.add(code)
                break
        battle.code = code
        battle.save(update_fields=["code"])


def noop(apps, schema_editor):
    """Reversing simply drops the column, so nothing to undo here."""


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleparticipant',
            name='answered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # 1. add the column without the unique constraint
        migrations.AddField(
            model_name='brainbattle',
            name='code',
            field=models.CharField(
                blank=True, db_index=True, default='',
                help_text='Short code participants type to join', max_length=8,
            ),
        ),
        # 2. give every existing row a real code
        migrations.RunPython(backfill_codes, noop),
        # 3. now the constraint can hold
        migrations.AlterField(
            model_name='brainbattle',
            name='code',
            field=models.CharField(
                blank=True, db_index=True,
                help_text='Short code participants type to join', max_length=8, unique=True,
            ),
        ),

        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('selected_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('seconds_taken', models.FloatField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curriculum.battleparticipant')),
            ],
            options={
                'ordering': ['question_index'],
                'unique_together': {('participant', 'question_index')},
            },
        ),
    ]
