# Generated by Django 6.0.4 on 2026-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_battleparticipant_answered_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
