# Generated by Django 6.0.4 on 2026-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_slide_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
