# Generated by Django 6.0.4 on 2026-04-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_slide_subject_material_quizquestion_quiz_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideContent',
            fields=[
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content', serialize=False, to='curriculum.slide')),
                ('is_extracted', models.BooleanField(default=False)),
                ('extraction_error', models.TextField(blank=True)),
                ('content_data', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
